# Site settings
title: Hiroki Oshima
email: geet1876@gmail.com
url: https://h-shima.github.io
description: "Hiroki Oshimaのポートフォリオサイトです"
keywords: "your keywords, separated by commas"
skills: "Web Engineer"
meta_author: Oshima Hiroki
encoding: utf-8

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/hiro_089k
  - title: bitbucket
    url: https://bitbucket.org/hirokioshima/
  - title: github
    url: https://github.com/h-shima

# Postal address (add as many lines as necessary)
address:
  - line: Machida, Tokyo

# Build settings
markdown: kramdown
permalink: pretty
